# coordinate system
spatial_reference:
  utm32: "ETRS 1989 UTM Zone 32N"
  utm33: "ETRS 1989 UTM Zone 33N"
  utm35: "ETRS 1989 UTM Zone 35N"

EPSG:
  utm32: 25832
  utm33: 25833
  utm35: 25835
  wgs84: 4326